
server.port = 8083
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

# Threshold value for similarity comparison between OCR results and financial data
similarity.threshold=0.
# Azure URL for OCR service
#azure.url=https://nasoft-ocr.cognitiveservices.azure.com/formrecognizer/documentModels/prebuilt-layout:analyze?pages=
# Azure API key for accessing Azure services
azure.key=92817e33e0c240d4a4b18ea7a7955771
# Version of the Azure OCR API
azure.url=https://nasoft-ocr.cognitiveservices.azure.com/documentintelligence/documentModels/prebuilt-layout:analyze?pages=
azure.version=&api-version=2024-11-30
#2023-07-31
# URL for fetching financial statements from the service
#finStatement.url=http://10.254.100.163:8024/finStatementApi/entity/list/
#finStatement.url=http://10.254.100.163:8027/finStatementApi/entity/list/
# URL for fetching financial statements from the internal network
#url = "http://10.254.100.163:8025/finStatementApi/entity/list/";
#finStatement.url=http://bnac.gdf.nacloud.tn:8033/finStatementApi/entity/list/
finStatement.url=http://localhost:8899/entity/list/

similarity.composite.weights.cosine=0.4
similarity.composite.weights.jaccard=0.3
similarity.composite.weights.levenshtein=0.3
similarity.minimum-acceptable=0.65
similarity.adaptive-threshold-percentile=75
similarity.threshold=0.7

